language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

after_success:
  - bash <(curl -s https://codecov.io/bash)

script: phpunit --configuration phpunit.xml.dist --coverage-clover=coverage.xml